oop-basic-intro-to-dom
js-tasks-ru/js-20210806_osoko007 pull request #4
Opened 2021-08-20 10:26 UTC by kipish0293

2021-08-20 10:27 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-08-20 13:09 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    constructor(data) {
если использовать аргументы по умолчанию, это может значительно улучшить читабельность кода:
```
  constructor({
    data = [],
    label = '',
    link = '',
    value = 0,
    formatHeading = data => data,
  } = {}) {
    this.data = data;
    this.label = label;
    this.link = link;
    this.value = formatHeading(value);

```

2021-08-20 13:09 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        this.isUndefined =  true
подумайте, нужно ли данное значение, либо мы можем от него отказаться?

2021-08-20 13:10 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +      this.label = Object.keys(this.data).includes('label') ? this.data.label : '';
подумайте, если задать параметры по умолчанию, упростит ли это данный код

2021-08-20 13:11 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    render() {
подумайте над этим методом, можно ли разбить его логику на несколько методов?

2021-08-20 13:11 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +      const headerChart = document.createElement('div');
создание шаблона компонента лучше организовывать через метод `innerHTML`, подробнее обсудим на занятии

2021-08-20 13:12 UTC, dosandk requested changes
пожалуйста попробуйте разбить метод `render` на несколько методов

2021-08-20 13:59 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-08-23 12:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-23 12:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-23 14:38 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-23 14:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-08-23 22:18 UTC, dosandk approved these changes
good 👍

2021-08-23 22:18 UTC, merged